version: '3'
services:
  dev:
    build: .
    command: >
      /bin/sh -c "cp -r /tmp/.ssh/* /root/.ssh/
      && chmod -R 0600 /root/.ssh/
      && git config --global alias.co checkout
      && git config --global alias.br branch
      && git config --global alias.ci commit
      && git config --global alias.st status
      && while sleep 1000; do :; done"
    volumes:
      - ..:/workspaces:delegated
      - ~/.ssh/:/tmp/.ssh/:ro
    env_file: devcontainer.env